name = "casflo"
main = "index.js"
compatibility_date = "2023-10-30"

# [PERBAIKAN] Gunakan sintaks yang benar dan tambahkan aturan untuk file .js
[[build.module_rules]]
type = "Text"
globs = ["**/*.html"]

[[build.module_rules]]
type = "Text"
globs = ["**/*.js"]