name = "casflo" # Ganti dengan nama worker Anda
main = "index.js"
compatibility_date = "2023-10-30"

# Perintah untuk Wrangler agar bisa menyertakan file .html sebagai teks
[rules]
type = "Text"
globs = ["**/*.html"]