name = "casflo"
main = "index.js"
compatibility_date = "2023-10-30"

# [BARU] Tambahkan bagian ini untuk memberitahu bundler cara mengimpor file
[build]
module_rules = [
  { type = "Text", globs = ["**/*.html"] }
]